#!/bin/bash

num1=${1?}
num2=${2?}

function bin2dec
{
    local bin_num=${1?}
    local dec_num=""

    dec_num=$((num=2#$bin_num))
    echo $dec_num
}

function dec2bin
{
    local bin_num=""
    local dec_num=${1?}

    bin_num=`echo "obase=2;$dec_num" | bc | awk '{printf("%08d\n",$0)}'`
    echo $bin_num
}

function sumbin
{
    local bin_num1=${1?}
    local bin_num2=${2?}

    local dec_num1=`bin2dec $bin_num1`
    local dec_num2=`bin2dec $bin_num2`

    local sumbin=""
    local sumdec=""
    sumdec=`echo "$dec_num1 + $dec_num2" | bc`
    sumbin=`dec2bin $sumdec `

    echo $sumbin
}

sumbin $num1 $num2
